general:
  strict_mode: false
columns:
  age:
    aliases:
    - 'Age '
    dtype: int
    missing: mode
    numeric_cleaning:
      strip: true
      remove_special_chars: true
    outliers:
      method: cap_percentile
      lower: 0.1
      upper: 0.9
  gender:
    aliases:
    - ' Gender'
    dtype: str
    missing: mode
    text_cleaning:
      strip: true
      title: true
      lower: false
      upper: false
    value_mapping:
      Male:
      - M
      - male
      Female:
      - F
      - fem
      - ''
  bmi:
    aliases:
    - BMI
    dtype: float
    missing: median
    numeric_cleaning:
      strip: true
      remove_special_chars: true
    outliers:
      method: cap_percentile
      lower: 0.1
      upper: 0.9
  children:
    aliases:
    - 'Children '
    dtype: int
    missing: mode
    numeric_cleaning:
      strip: true
      remove_special_chars: true
    outliers:
      method: cap_percentile
      lower: 0.1
      upper: 0.9
  smoker:
    aliases:
    - Smoker?
    dtype: str
    missing: mode
    text_cleaning:
      strip: true
      title: true
      lower: false
      upper: false
    value_mapping:
      'Yes':
      - 'yes'
      - Y
      - smoker
      'No':
      - N
      - 'no'
      - non-smoker
  state:
    aliases:
    - ' State '
    dtype: str
    missing: mode
    text_cleaning:
      strip: true
      title: true
      lower: false
      upper: false
  hospital_bill:
    aliases:
    - Hospital_Bill
    dtype: float
    missing: drop
    numeric_cleaning:
      strip: true
      remove_special_chars: true
    outliers:
      method: cap_percentile
      lower: 0.1
      upper: 0.9
duplicates:
  drop: true
